
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the sjkpdev07ContextData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.sjkpdev07ContextDataService sjkpdev07ContextData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.sjkpdev07ContextData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.sjkpdev07ContextData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.sjkpdev07ContextDataService> sjkpdev07ContextData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.sjkpdev07ContextData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.sjkpdev07ContextDataService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.sjkpdev07ContextDataService>.Entry
                    sjkpdev07ContextData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.sjkpdev07ContextDataService>.Entry(
                        "sjkpdev07ContextData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._sjkpdev07ContextData_Stub);
                private static void _sjkpdev07ContextData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.sjkpdev07ContextDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._sjkpdev07ContextData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.sjkpdev07ContextDataService>.Data _sjkpdev07ContextData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the sjkpdev07ContextData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class sjkpdev07ContextData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public sjkpdev07ContextData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the AccountSet entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Account> AccountSet
        {
            get
            {
                return global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.GetValue(this, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.PropertySetProperties.AccountSet);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="AccountId">
        /// The value of the 'AccountId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Account AccountSet_Single(global::System.Nullable<global::System.Guid> AccountId)
        {
            return this.Details.Methods.AccountSet_Single.CreateInvocation(AccountId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="AccountId">
        /// The value of the 'AccountId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Account AccountSet_SingleOrDefault(global::System.Nullable<global::System.Guid> AccountId)
        {
            return this.Details.Methods.AccountSet_SingleOrDefault.CreateInvocation(AccountId).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.PropertySet, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.MethodSetProperties.AccountSet_Single;
                var initializePropertyEntry = global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.PropertySetProperties.AccountSet;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account> AccountSet_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.MethodSetProperties.AccountSet_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account> AccountSet_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.MethodSetProperties.AccountSet_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account> AccountSet
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.PropertySetProperties.AccountSet) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Entry
                    AccountSet_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Entry(
                        "AccountSet_Single",
                        global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.MethodSetProperties._AccountSet_Single_Stub);
                private static void _AccountSet_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Data> c, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass d, object sf)
                {
                    c(d, ref d._AccountSet_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Entry
                    AccountSet_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Entry(
                        "AccountSet_SingleOrDefault",
                        global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.MethodSetProperties._AccountSet_SingleOrDefault_Stub);
                private static void _AccountSet_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Data> c, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass d, object sf)
                {
                    c(d, ref d._AccountSet_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Entry
                    AccountSet = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Entry(
                        "AccountSet",
                        global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass.PropertySetProperties._AccountSet_Stub);
                private static void _AccountSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Data> c, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass d, object sf)
                {
                    c(d, ref d._AccountSet, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Data _AccountSet;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Data _AccountSet_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.sjkpdev07ContextData, global::LightSwitchApplication.sjkpdev07ContextData.DetailsClass, global::LightSwitchApplication.Account>.Data _AccountSet_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
